// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  modules: [
    "@nuxt/eslint",
    "@nuxt/image",
    "@nuxt/ui",
    "@nuxtjs/i18n",
    "@nuxt/content",
    "@nuxtjs/sitemap",
    "@vueuse/nuxt",
    "nuxt-og-image",
    "motion-v/nuxt",
  ],
  site: {
    url: "https://y-l.fr",
    name: "Youenn Le Gouedec",
  },
  sitemap: {
    autoLastmod: true,
  },
  i18n: {
    baseUrl: "https://y-l.fr",
    defaultLocale: "fr",
    strategy: "prefix_except_default",
    detectBrowserLanguage: false,
    locales: [
      {
        code: "fr",
        name: "Français",
        language: "fr-FR",
        file: "fr.json",
      },
      {
        code: "en",
        name: "English",
        language: "en-US",
        file: "en.json",
      },
    ],
  },
  devtools: { enabled: true },
  css: ["~/assets/css/main.css"],
  compatibilityDate: "2025-07-15",
  nitro: {
    prerender: {
      routes: [
        "/",
        "/en",
        "/developpeur-laravel",
        "/developpeur-vue-nuxt",
        "/developpement-saas",
        "/audit-code-laravel",
        "/resume",
        "/en/developpeur-laravel",
        "/en/developpeur-vue-nuxt",
        "/en/developpement-saas",
        "/en/audit-code-laravel",
        "/en/resume",
        "/projets/notenn",
        "/projets/webvite",
        "/projets/saasterkit",
        "/projets/frankenphp-websocket",
        "/en/projets/notenn",
        "/en/projets/webvite",
        "/en/projets/saasterkit",
        "/en/projets/frankenphp-websocket",
      ],
      crawlLinks: true,
      ignore: ["/en/sitemap.xml"],
    },
  },
  content: {
    build: {
      markdown: {
        highlight: {
          langs: ["vue", "bash", "yml", "yaml", "dockerfile"],
        },
        toc: {
          searchDepth: 1,
        },
      },
    },
  },
  icon: {
    clientBundle: {
      scan: true,
      sizeLimitKb: 256,
      icons: [
        "lucide:calendar",
        "lucide:activity",
        "lucide:arrow-right",
        "lucide:arrow-left",
        "lucide:blocks",
        "lucide:book-open",
        "lucide:chart-no-axes-combined",
        "lucide:check-circle",
        "lucide:chevron-down",
        "lucide:chevron-left",
        "lucide:chevron-right",
        "lucide:copy",
        "lucide:credit-card",
        "lucide:database",
        "lucide:external-link",
        "lucide:gauge",
        "lucide:git-branch",
        "lucide:hash",
        "lucide:languages",
        "lucide:layout-dashboard",
        "lucide:layout-template",
        "lucide:list-checks",
        "lucide:mail",
        "lucide:map-pin",
        "lucide:monitor-smartphone",
        "lucide:moon",
        "lucide:network",
        "lucide:panels-top-left",
        "lucide:phone",
        "lucide:plug",
        "lucide:printer",
        "lucide:rocket",
        "lucide:scan-search",
        "lucide:search-check",
        "lucide:server-cog",
        "lucide:shield-check",
        "lucide:sun",
        "lucide:wrench",
        "simple-icons:github",
        "simple-icons:linkedin",
        "simple-icons:malt",
        "simple-icons:x",
      ],
    },
  },
});
